
#set($command = $helper.getByName($command-name, $robot))

\#include "#class($command.name).h"

#class($command.name)::#class($command.name)() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
#@autogenerated_code("requires", "        ")
#parse("${exporter-path}Command-requires.cpp")
#end
}

// Called just before this Command runs the first time
void ExampleCommand::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void ExampleCommand::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool ExampleCommand::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void ExampleCommand::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ExampleCommand::Interrupted() {
}
