\#include "OI.h"

${helper.getImports($robot, "OI")}

OI::OI() {
	// Process operator interface input here.
#@autogenerated_code("constructors", "        ")
#parse("${exporter-path}OI-constructors.cpp")
#end
}
