#ifndef OI_H
\#define OI_H

#@autogenerated_code("includes", "")
#parse("${exporter-path}OI-includes.h")
#end
\#include "WPILib.h"

class OI {
private:
public:
#@autogenerated_code("declarations", "    ")
#parse("${exporter-path}OI-declarations.h")
#end
	OI();
};

#endif
