#ifndef OI_H
\#define OI_H

\#include "WPILib.h"

class OI {
private:
public:
#@autogenerated_code("declarations", "	")
#parse("${exporter-path}OI-declarations.h")
#end
	OI();
};

#endif
