#set($subsystem = $helper.getByName($subsystem-name, $robot))
#header()

#ifndef #constant($subsystem.name)_H
\#define #constant($subsystem.name)_H

\#include "Commands/PIDSubsystem.h"
\#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($subsystem.name): public PIDSubsystem {
 public:
#@autogenerated_code("declarations", "	")
#parse("${exporter-path}Subsystem-declarations.h")
#end
	#class($subsystem.name)();
	double ReturnPIDInput();
	void UsePIDOutput(double output);
	void InitDefaultCommand();
};

#endif
