#ifndef EXAMPLE_SUBSYSTEM_H
\#define EXAMPLE_SUBSYSTEM_H
\#include "Commands/Subsystem.h"
\#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ExampleSubsystem: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
#@autogenerated_code("declarations", "    ")
#parse("${exporter-path}Subsystem-declarations.h")
#end
	ExampleSubsystem();
	void InitDefaultCommand();
};

#endif
