#header()

#ifndef _ROBOT_H
\#define _ROBOT_H

\#include "frc/WPILib.h"
\#include "frc/commands/Command.h"
\#include "frc/livewindow/LiveWindow.h"

#@autogenerated_code("includes", "")
#parse("${exporter_path}CommandBasedRobot-includes.h")
#end
\#include "OI.h"

class Robot : public frc::TimedRobot {
public:
	frc::Command* autonomousCommand = nullptr;
	static std::unique_ptr<OI> oi;
	frc::LiveWindow *lw = frc::LiveWindow::GetInstance();
	frc::SendableChooser<frc::Command*> chooser;
#@autogenerated_code("declarations", "	")
#parse("${exporter_path}CommandBasedRobot-declarations.cpp")
#end
	void RobotInit() override;
	void DisabledInit() override;
	void DisabledPeriodic() override;
	void AutonomousInit() override;
	void AutonomousPeriodic() override;
	void TeleopInit() override;
	void TeleopPeriodic() override;
};
#endif
