#header()

#set($command = $helper.getByName($command_name, $robot))

#pragma once

\#include "frc/commands/CommandGroup.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($command.name): public frc::CommandGroup {
public:

#@autogenerated_code("constructor", "    ")
#parse("${exporter_path}Command-constructor-header.h")
#end

private:

};
