#header()

#ifndef _ROBOT_H
\#define _ROBOT_H

\#include "WPILib.h"
\#include "Commands/Command.h"
\#include "RobotMap.h"
\#include "LiveWindow/LiveWindow.h"

#@autogenerated_code("includes", "")
#parse("${exporter-path}CommandBasedRobot-includes.h")
#end
\#include "OI.h"

class Robot : public IterativeRobot {
public:
	std::unique_ptr<Command> autonomousCommand;
	static std::unique_ptr<OI> oi;
	LiveWindow *lw = LiveWindow::GetInstance();
#@autogenerated_code("declarations", "	")
#parse("${exporter-path}CommandBasedRobot-declarations.cpp")
#end
	void RobotInit() override;
	void DisabledInit() override;
	void DisabledPeriodic() override;
	void AutonomousInit() override;
	void AutonomousPeriodic() override;
	void TeleopInit() override;
	void TeleopPeriodic() override;
	void TestPeriodic() override;
};
#endif
