#set($command = $helper.getByName($command_name, $robot))
#macro( klass $cmd ) frc2::CommandHelper<#type($cmd), $cmd.name>#end
#header()
// ROBOTBUILDER TYPE: Command.

#pragma once

#@autogenerated_code("includes", "    ")
#parse("${exporter_path}command-includes.h")
#end

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($command.name): public frc2::CommandHelper<#type($command), #class($command.name)> {
public:
#@autogenerated_code("constructor", "    ")
#parse("${exporter_path}Command-constructor-header.h")
#end

void Initialize() override;
void Execute() override;
bool IsFinished() override;
void End(bool interrupted) override;
bool RunsWhenDisabled() const override;


private:
#@autogenerated_code("variables", "    ")
#parse("${exporter_path}Command-constructor-variables.h")
#end
};
