#set($command = $helper.getByName($command_name, $robot))

#header()
// ROBOTBUILDER TYPE: ConditionalCommand.

#pragma once

#@autogenerated_code("includes", "")
#parse("${exporter_path}ConditionalCommand-includes.h")
#end
class #class($command.name) : public frc::ConditionalCommand {
public:
#@autogenerated_code("constructor", "    ")
#parse("${exporter_path}ConditionalCommand-constructor-header.h")
#end
protected:
virtual bool Condition();
};
