#set($command = $helper.getByName($command-name, $robot))
#header()

\#include "#class($command.name).h"

#@autogenerated_code("constructor", "    ")
#parse("${exporter-path}ConditionalCommand-constructor.cpp")
#end

bool #class($command.name)::Condition(){
	return false;
}
