#set($command = $helper.getByName($command-name, $robot))
#header()

#ifndef #constant($command.name)_H
\#define #constant($command.name)_H


\#include "Commands/Subsystem.h"
\#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($command.name): public frc::InstantCommand {
public:
#@autogenerated_code("constructor", "    ")
#parse("${exporter-path}Command-constructor-header.h")
#end

	void Initialize() override;

private:
#@autogenerated_code("variables", "	")
#parse("${exporter-path}Command-constructor-variables.h")
#end
};

#endif
