#set($command = $helper.getByName($command_name, $robot))
#header()

#pragma once

\#include "frc2/command/InstantCommand.h"
\#include "subsystems/#class(${command.getProperty("Requires").getValue()}).h"

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($command.name): public frc2::InstantCommand {
public:
#@autogenerated_code("constructor", "    ")
#parse("${exporter_path}Command-constructor-header.h")
#end

    void Initialize() override;

private:
#@autogenerated_code("variables", "    ")
#parse("${exporter_path}Command-constructor-variables.h")
#end
};

