#set($command = $helper.getByName($command_name, $robot))
#set($params = $command.getProperty("Parameters").getValue())
#header()

\#include "commands/#class($command.name).h"

#@autogenerated_code("constructor", "")
#parse("${exporter_path}Command-constructor.cpp")
#end

}

// Called once when this command runs
void #class($command.name)::Initialize() {

}

