#header()

\#include "OI.h"

#@autogenerated_code("includes", "")
#parse("${exporter_path}OI-includes.h")
#end

OI::OI() {
    // Process operator interface input here.
#@autogenerated_code("constructors", "    ")
#parse("${exporter_path}OI-constructors.cpp")
#end
}

#@autogenerated_code("functions", "")
#parse("${exporter_path}OI-functions.cpp")
#end
