#header()

#pragma once

\#include "frc/Joystick.h"
\#include "frc/buttons/JoystickButton.h"

class OI {
private:
#@autogenerated_code("declarations", "	")
#parse("${exporter_path}OI-declarations.h")
#end
public:
	OI();

#@autogenerated_code("prototypes", "	")
#parse("${exporter_path}OI-prototypes.h")
#end
};

