#set($command = $helper.getByName($command_name, $robot))

#header()

#pragma once

\#include "frc2/Command/PIDCommand.h"
\#include <frc2/command/CommandHelper.h>
\#include "Subsystems/#class(${command.getProperty("Requires").getValue()}).h"

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($command.name): public frc2::CommandHelper<frc2::PIDCommand, #class($command.name)> {
public:
#@autogenerated_code("constructor", "    ")
#parse("${exporter_path}Command-constructor-header.h")
#end

    double ReturnPIDInput();
    void UsePIDOutput(double output);
	void Initialize();
	void Execute();
	bool IsFinished();
	void End();
	void Interrupted();

#@autogenerated_code("cmdpidgetters","	")
#parse("${exporter_path}Subsystem-pidgetters.h")
#end
private:
#@autogenerated_code("variables", "	")
#parse("${exporter_path}Command-constructor-variables.h")
#end
};

