#header()

#set($command = $helper.getByName($command-name, $robot))

#@autogenerated_code("constructor", "    ")
#parse("${exporter-path}Command-constructor.cpp")
#end
#@autogenerated_code("pid", "        ")
#parse("${exporter-path}PIDCommand-pid.cpp")
#end

        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
#@autogenerated_code("requires", "        ")
#parse("${exporter-path}Command-requires.cpp")
#end
}

double #class($command.name)::returnPIDInput() {
    // Return your input value for the PID loop
    // e.g. a sensor, like a potentiometer:
    // yourPot.getAverageVoltage() / kYourMaxVoltage;

#@autogenerated_code("source", "        ")
#parse("${exporter-path}PIDCommand-source.cpp")
#end
    }

void #class($command.name)::usePIDOutput(double output) {
    // Use output to drive your system, like a motor
    // e.g. yourMotor.set(output);

#@autogenerated_code("output", "        ")
#parse("${exporter-path}PIDCommand-output.cpp")
#end
}

// Called just before this Command runs the first time
void #classinitialize() {
}

// Called repeatedly when this Command is scheduled to run
void #class($command.name)::execute() {
}

// Make this return true when this Command no longer needs to run execute()
boolean #class($command.name)::isFinished() {
    return false;
}

// Called once after isFinished returns true

void #class($command.name)::end() {
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
@Override
void #class($command.name)::interrupted() {
}