#set($subsystem = $helper.getByName($subsystem-name, $robot))
#header()

#ifndef #constant($subsystem.name)_H
\#define #constant($subsystem.name)_H

\#include "frc/commands/PIDSubsystem.h"
\#include "frc/WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($subsystem.name): public frc::PIDSubsystem {

#@autogenerated_code("declarations", "	")
#parse("${exporter-path}Subsystem-declarations.h")
#end
 public:
	#class($subsystem.name)();
	double ReturnPIDInput() override;
	void UsePIDOutput(double output) override;
	void InitDefaultCommand() override;
#@autogenerated_code("constants", "	")
#parse("${exporter-path}Subsystem-constants.h")
#end

#@autogenerated_code("cmdpidgetters","	")
#parse("${exporter-path}Subsystem-pidgetters.h")
#end
};

#endif
