#set($subsystem = $helper.getByName($subsystem_name, $robot))
#header()

#pragma once

\#include "frc2/Command/PIDSubsystem.h"

#@autogenerated_code("includes", "")
#parse("${exporter_path}Subsystem-includes.h")
#end

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($subsystem.name): public frc2::PIDSubsystem {
private:
#@autogenerated_code("declarations", "    ")
#parse("${exporter_path}Subsystem-declarations.h")
#end
public:
    #class($subsystem.name)();
    double ReturnPIDInput();
    void UsePIDOutput(double output);
    void InitDefaultCommand();
#@autogenerated_code("constants", "    ")
#parse("${exporter_path}Subsystem-constants.h")
#end

#@autogenerated_code("cmdpidgetters","    ")
#parse("${exporter_path}Subsystem-pidgetters.h")
#end
};

