#set($subsystem = $helper.getByName($subsystem_name, $robot))
#header()

#pragma once

\#include "frc/commands/PIDSubsystem.h"

#@autogenerated_code("includes", "")
#parse("${exporter_path}Subsystem-includes.h")
#end

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($subsystem.name): public frc::PIDSubsystem {

#@autogenerated_code("declarations", "	")
#parse("${exporter_path}Subsystem-declarations.h")
#end
 public:
	#class($subsystem.name)();
	double ReturnPIDInput() override;
	void UsePIDOutput(double output) override;
	void InitDefaultCommand() override;
#@autogenerated_code("constants", "	")
#parse("${exporter_path}Subsystem-constants.h")
#end

#@autogenerated_code("cmdpidgetters","	")
#parse("${exporter_path}Subsystem-pidgetters.h")
#end
};

