#header()

#@autogenerated_code("includes", "")
#parse("${exporter-path}RobotMap-includes.cpp")
#end

#@autogenerated_code("allocation", "")
#parse("${exporter-path}RobotMap-allocation.cpp")
#end

void RobotMap::init() {
#@autogenerated_code("constructors", "    ")
#parse("${exporter-path}RobotMap-constructors.cpp")
#end
}
