#header()

\#include "RobotContainer.h"

#@autogenerated_code("includes", "")
#parse("${exporter_path}OI-includes.h")
#end

RobotContainer::RobotContainer() : m_autonomousCommand(){
    // Process operator interface input here.
#@autogenerated_code("constructors", "    ")
#parse("${exporter_path}OI-constructors.cpp")
#end
}

#@autogenerated_code("functions", "")
#parse("${exporter_path}OI-functions.cpp")
#end


frc2::Command* RobotContainer::GetAutonomousCommand() {
  // An example command will be run in autonomous
  return &m_autonomousCommand;
}