#set($command = $robot.getProperty("Autonomous Command").getValue())

#foreach( $component in $components )
#if ($helper.exportsTo("OI", $component)
    && "#type($component)" != "Joystick" 
    && ("#constructor($component)" != "" || "#extra($component)" != ""))
        #constructor($component)
        ${Collections.reverse($commands)}
        #foreach ($command in $commands)
                #if($command.name == $component.getProperty("Command").value)
                        #set($params = $component.getProperty("Parameters").getValue())
                        #variable($component.name).$component.getProperty("When to Run").getValue()(#new_command_instantiation($component,$command,$params)#if($component.getProperty("Add Timeout").value == true).withTimeout($component.getProperty("Timeout").value));#else#if($command.getProperty("Add Timeout").value == true).withTimeout($command.getProperty("Timeout").value));#else);#end#end
                #end
        #end
#end
#end

#header()

#pragma once

\#include "frc/Joystick.h"
\#include "frc2/command/Command.h"

\#include "Commands/#class($command).h"

#foreach( $component in $components )
#if ($component.getBase().getType() == "Command"
     && $component.getProperty("Button on SmartDashboard").getValue())
        #if( $component.getProperty("Parameter presets").getValue().isEmpty() )
                #if ($component.getProperty("Requires").getValue() != "None")
\#include "Subsystems/#class(${component.getProperty("Requires").getValue()}).h"
               #end
        #end
#end
#end

#@autogenerated_code("prototypes", "	")
#parse("${exporter_path}OI-includes.h")
#end

class RobotContainer {

public:
	RobotContainer();
	frc2::Command* GetAutonomousCommand();

#@autogenerated_code("prototypes", "	")
#parse("${exporter_path}OI-prototypes.h")
#end

private:


#foreach( $component in $components )
#if ($component.getBase().getType() == "Command"
     && $component.getProperty("Button on SmartDashboard").getValue())
        #if( $component.getProperty("Parameter presets").getValue().isEmpty() )
                #if ($component.getProperty("Requires").getValue() != "None")
#class(${component.getProperty("Requires").getValue()})* m_#required_subsystem($component);
               #end
        #end
#end
#end

#@autogenerated_code("declarations", "	")
#parse("${exporter_path}OI-declarations.h")
#end

#class($command) m_autonomousCommand;

void ConfigureButtonBindings();
};