#header()

\#include "RobotMap.h"
\#include "LiveWindow/LiveWindow.h"
${helper.getImports($robot, "RobotMap")}

#@autogenerated_code("allocation", "")
#parse("${exporter-path}RobotMap-allocation.cpp")
#end

void RobotMap::init() {
#@autogenerated_code("constructors", "	")
#parse("${exporter-path}RobotMap-constructors.cpp")
#end
}
