#set($command = $robot.getProperty("Autonomous Command").getValue())

#header()

#pragma once

\#include "frc/Joystick.h"
\#include "frc2/command/Command.h"

\#include "Commands/#class($command).h"

class RobotContainer {

public:
	RobotContainer();
	frc2::Command* GetAutonomousCommand();

#@autogenerated_code("prototypes", "	")
#parse("${exporter_path}OI-prototypes.h")
#end

private:
#@autogenerated_code("declarations", "	")
#parse("${exporter_path}OI-declarations.h")
#end

#class($command) m_autonomousCommand;

void ConfigureButtonBindings();
};