#header()

#@autogenerated_code("constructor", "")
#parse("${exporter_path}Command-constructor.cpp")
#end ##autogenerated
    // Add your commands here, e.g.
    // AddCommands(FooCommand(), BarCommand());


}

bool #class($command.name)::RunsWhenDisabled() const {
#@autogenerated_code("disabled", "    ")
#parse("${exporter_path}Command-disabled.cpp")
#end
}