#header()

#set($command = $helper.getByName($command_name, $robot))

#pragma once

#@autogenerated_code("includes", "    ")
#parse("${exporter_path}command-includes.h")
#end
\#include <frc2/command/SequentialCommandGroup.h>

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($command.name): public frc2:: CommandHelper<frc2::SequentialCommandGroup,
                                 #class($command.name)>{
public:

#@autogenerated_code("constructor", "    ")
#parse("${exporter_path}Command-constructor-header.h")
#end

bool RunsWhenDisabled() const override;

private:
#@autogenerated_code("variables", "    ")
#parse("${exporter_path}Command-constructor-variables.h")
#end
};

