#set($command = $helper.getByName($command_name, $robot))
#header()

#pragma once

#@autogenerated_code("includes", "    ")
#parse("${exporter_path}command-includes.h")
#end

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($command.name): public frc2::CommandHelper<frc2::CommandBase, #class($command.name)> {
public:
#@autogenerated_code("constructor", "    ")
#parse("${exporter_path}SetpointCommand-constructor-header.h")
#end

    void Initialize() override;
    void Execute() override;
    bool IsFinished() override;
    void End(bool interrupted) override;

private:
#@autogenerated_code("variables", "    ")
    double m_setpoint;
    #class(${command.getProperty("Requires").getValue()})* m_#variable(${command.getProperty("Requires").getValue().toLowerCase()});
#end
};

