#set($subsystem = $helper.getByName($subsystem-name, $robot))
#macro( klass $cmd )#if( "#type($cmd)" == "" )frc::Subsystem#else#type($cmd)#end#end
#header()

#ifndef #constant($subsystem.name)_H
\#define #constant($subsystem.name)_H
\#include "Commands/Subsystem.h"
\#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($subsystem.name): public #klass($subsystem) {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
#@autogenerated_code("declarations", "	")
#parse("${exporter-path}Subsystem-declarations.h")
#end
public:
	#class($subsystem.name)();
	void InitDefaultCommand() override;
	void Periodic() override;
#@autogenerated_code("constants", "	")
#parse("${exporter-path}Subsystem-constants.h")
#end
};

#endif
