#set($command = $helper.getByName($command_name, $robot))

#class($command.name)::#class($command.name)(double timeout) : frc::TimedCommand(timeout) {
    // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
#@autogenerated_code("requires", "    ")
#parse("${exporter_path}Command-requires.cpp")
#end
#if ( $command.getProperty("Run When Disabled").getValue() )
    SetRunWhenDisabled(true);
#end
}
