#set($command = $helper.getByName($command-name, $robot))

#class($command.name)::#class($command.name)(double timeout) : TimedCommand(timeout) {
    // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
#@autogenerated_code("requires", "    ")
#parse("${exporter-path}Command-requires.cpp")
#end
}
