#set($command = $helper.getByName($command-name, $robot))
#header()

#ifndef #constant($command.name)_H
\#define #constant($command.name)_H


\#include "Commands/Subsystem.h"
\#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($command.name): public TimedCommand {
public:
#@autogenerated_code("constructor", "    ")
#parse("${exporter-path}TimedCommand-constructor-header.h")
#end

	virtual void Initialize();
	virtual void Execute();
	virtual void End();
	virtual void Interrupted();

private:
#@autogenerated_code("variables", "    ")
#end
};

#endif
