#set($command = $helper.getByName($command_name, $robot))
#header()
// ROBOTBUILDER TYPE: WaitCommand.

#pragma once

\#include <units/time.h>
\#include "frc2/command/WaitCommand.h"

#@autogenerated_code("includes", "    ")
#parse("${exporter_path}command-includes.h")
#end

/**
 *
 *
 * @author ExampleAuthor
 */
class #class($command.name): public frc2::WaitCommand {
public:
#@autogenerated_code("constructor", "    ")
#parse("${exporter_path}WaitCommand-constructor-header.h")
#end
    void Initialize() override;
    void Execute() override;
    void End(bool interrupted) override;
    bool RunsWhenDisabled() const override;
private:
#@autogenerated_code("variables", "    ")
#parse("${exporter_path}Command-constructor-variables.h")
#end
};

