#header()
// ROBOTBUILDER TYPE: WaitCommand.

#set($command = $helper.getByName($command_name, $robot))

\#include "commands/#class($command.name).h"

#@autogenerated_code("constructor", "")
#parse("${exporter_path}WaitCommand-constructor.cpp")
#end

}

// Called just before this Command runs the first time
void #class($command.name)::Initialize() {
    WaitCommand::Initialize();
}

// Called repeatedly when this Command is scheduled to run
void #class($command.name)::Execute() {

}

// Called once after isFinished returns true
void #class($command.name)::End(bool interrupted) {
    WaitCommand::End(interrupted);
}

bool #class($command.name)::RunsWhenDisabled() const {
#@autogenerated_code("disabled", "    ")
#parse("${exporter_path}Command-disabled.cpp")
#end
}