#header()

package ${package}.commands;
#set($command = $helper.getByName($command-name, $robot))
#set($params = $command.getProperty("Parameters").getValue())

import edu.wpi.first.wpilibj.command.Command;
import ${package}.Robot;

/**
 *
 */
public class #class($command.name) extends Command {

    #@autogenerated_code("parameters", "        ")
    #parse("${exporter-path}Command-constructor.java")
    #end
    #if( $params.size() > 0 )
        #@autogenerated_code("requires", "        ")
        #parse("${exporter-path}Command-requires.java")
        #end
    }
    /**
     * The default constructor used to send this command to the
     * SmartDashboard and be controlled from there. Teams should not use
     * this constructor in their robot programs.
     */
    #end
    public #class($command.name)() {
        super();
        #if( $params.size() > 0 )
        // Uncomment the lines below to start setting the default values
        // of the variables:
        #foreach( $param in $params )
        // m_$param.getName() =
        #end#end
        #@autogenerated_code("requires", "        ")
        #parse("${exporter-path}Command-requires.java")
        #end
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
