#header()

package ${package}.commands.commandgroups;
#set($command = $helper.getByName($command-name, $robot))
#set($commandDescriptors = $command.getProperty("Commands").getValue())

import edu.wpi.first.wpilibj.command.BBCommandGroup;
import ${package}.subsystems.*;

/**
 *
 */
public class #class($command.name) extends BBCommandGroup {


#@autogenerated_code("parameters", "    ")
#parse("${exporter-path}CommandGroup-constructor.java")
#end##autogenerated
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
#@autogenerated_code("command_declarations", "        ")
#parse("${exporter-path}CommandGroup-declarations.java")
#end ##autogenerated

    } ## end constructor

}
