#header()

package ${package}.commands;
#set($command = $helper.getByName($command-name, $robot))

import edu.wpi.first.wpilibj.command.ConditionalCommand;
import ${package}.Robot;

/**
 *
 */
public class #class($command.name) extends ConditionalCommand {


#@autogenerated_code("constructor", "    ")
#parse("${exporter-path}ConditionalCommand-constructor.java")
#end

    }

    protected boolean condition(){
        return false;//TODO: Auto Generated method stub
    }
}
