#header()

package ${package}.commands;
#set($command = $helper.getByName($command-name, $robot))
#set($params = $command.getProperty("Parameters").getValue())
import edu.wpi.first.wpilibj.command.InstantCommand;
import ${package}.Robot;

/**
 *
 */
public class #class($command.name) extends InstantCommand {

#@autogenerated_code("variable_declarations", "    ")
#parse("${exporter-path}Command-variable-declarations.java")
#end

#@autogenerated_code("constructor", "    ")
#parse("${exporter-path}Command-constructor.java")
#end
#@autogenerated_code("variable_setting", "        ")
#parse("${exporter-path}Command-variable-setting.java")
#end
#@autogenerated_code("requires", "        ")
#parse("${exporter-path}Command-requires.java")
#end
    }

    // Called once when this command runs
    @Override
    protected void initialize() {
    }

}
