#header()

package ${package}.commands;
#set($command = $helper.getByName($command_name, $robot))
#set($params = $command.getProperty("Parameters").getValue())
#macro( klass $cmd )#if( "#type($cmd)" == "" )CommandBase#else#type($cmd)#end#end
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import ${package}.Robot;
#@autogenerated_code("imports", "")
#parse("${exporter_path}SequentialCommandGroup-imports.java")
#end

/**
 *
 */
public class #class($command.name) extends SequentialCommandGroup {
/**
   * Creates a new ComplexAuto.
   *
   * @param0   The drive subsystem this command will run on
   * @param1   The hatch subsystem this command will run on
   * @paramN   The hatch subsystem this command will run on
   */
#@autogenerated_code("constructors", "    ")
#parse("${exporter_path}SequentialCommandGroup-constructors.java")
#end
    addCommands(
        // Add Commands here:
        // Also add parrallel commands using the
        //
        // addCommands(
        //      new command1(argsN, subsystem),
        //      parallel(
        //          new command2(argsN, subsystem),
        //          new command3(argsN, subsystem)
        //      )    
        //  );
#@autogenerated_code("add commands", "        ")
#parse("${exporter_path}SequentialCommandGroup-add_commands.java")
#end


    );
    }
}
