#header()

package ${package}.commands;
#set($command = $helper.getByName($command-name, $robot))

import edu.wpi.first.wpilibj.command.Command;
import ${package}.Robot;

/**
 *
 */
public class #class($command.name) extends Command {

#@autogenerated_code("parameters", "        ")
#parse("${exporter-path}Command-constructor.java")
#end
#@autogenerated_code("requires", "        ")
#parse("${exporter-path}Command-requires.java")
#end
    }

    /**
     * The default constructor used to send this command to the
     * SmartDashboard and be controlled from there. Teams should not use
     * this constructor in their robot programs.
     */
    public #class($command.name)() {
        super();
        // Uncomment the line below to set the default setpoint
        // m_setpoint =
        #@autogenerated_code("requires", "        ")
        #parse("${exporter-path}Command-requires.java")
        #end
    }

    // Called just before this Command runs the first time
    protected void initialize() {
#@autogenerated_code("initialize", "        ")
#parse("${exporter-path}SetpointCommand-initialize.java")
#end
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
#@autogenerated_code("isFinished", "        ")
#parse("${exporter-path}SetpointCommand-isFinished.java")
#end
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
