#header()

package ${package}.commands;
#set($command = $helper.getByName($command_name, $robot))

import edu.wpi.first.wpilibj2.command.CommandBase;
import ${package}.Robot;
#@autogenerated_code("imports", "")
#parse("${exporter_path}SetpointCommand-imports.java")
#end

/**
 *
 */
public class #class($command.name) extends CommandBase {

#@autogenerated_code("variable_declarations", "    ")
#parse("${exporter_path}Command-variable-declarations.java")
#end

#@autogenerated_code("constructors", "    ")
#parse("${exporter_path}SetpointCommand-constructors.java")
#end
#@autogenerated_code("variable_setting", "        ")
#parse("${exporter_path}Command-variable-setting.java")
#end
#@autogenerated_code("requires", "        ")
#parse("${exporter_path}Command-requires.java")
#end
    }

    // Called just before this Command runs the first time
    @Override
    public void initialize() {
#@autogenerated_code("initialize", "        ")
#parse("${exporter_path}SetpointCommand-initialize.java")
#end
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    public boolean isFinished() {
#@autogenerated_code("isFinished", "        ")
#parse("${exporter_path}SetpointCommand-isFinished.java")
#end
    }

    // Called once after isFinished returns true
    @Override
    public void end(boolean interrupted) {
    
    }
   
}
