#header()

package ${package}.subsystems;
#set($subsystem = $helper.getByName($subsystem_name, $robot))
#macro( klass $cmd )#if( "#type($cmd)" == "" ) SubsystemBase #else#type($cmd)#end#end


import ${package}.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

#@autogenerated_code("imports", "")
#parse("${exporter_path}Subsystem-imports.java")
#end


/**
 *
 */
public class #class($subsystem.name) extends #klass($subsystem) {
#@autogenerated_code("constants", "    ")
#parse("${exporter_path}Subsystem-constants.java")
#end

#@autogenerated_code("declarations", "    ")
#parse("${exporter_path}Subsystem-declarations.java")
#end
    
    /**
    *
    */
    public #class($subsystem.name)() {
#@autogenerated_code("constructors", "        ")
#parse("${exporter_path}Subsystem-constructors.java")
#end
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        super.periodic();

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

