package ${package}.commands;
#set($command = $helper.getByName($command, $robot))
/**
 *
 */
public class  #class($command.name) extends CommandBase {

    public #class($command.name)() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
#@autogenerated_code("requires", "        ")
#if ($command.getProperty("Requires") != "None")
        requires(#variable($command.getProperty("Requires")));
#end
#end
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
