package ${package}.subsystems;
#set($subsystem = $helper.getByName($subsystem, $robot))

import ${package}.RobotMap;
import ${package}.commands.*;
${helper.getImports($subsystem, "RobotMap")}
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ${helper.className($subsystem.name)} extends Subsystem {
    // The following variables are automatically assigned by
    // robotbuilder and will be updated the next time you export to
    // Java from robot builder. Do not put any code or make any change
    // in the following block or it will be lost on an update. To
    // prevent this subsystem from being automatically updated, delete
    // the following line.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM
#foreach ($component in $components)
#if ($component.subsystem == $subsystem.subsystem && $component != $subsystem)
    ${helper.classOf($component)} ${helper.variableName($component.name)} = RobotMap.${helper.constantName($component.fullName)};
#end
#end
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
	// The following variables are automatically assigned by
	// robotbuilder and will be updated the next time you export to
	// Java from robot builder. Do not put any code or make any change
	// in the following block or it will be lost on an update. To
	// prevent this subsystem from being automatically updated, delete
	// the following line.
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
#if ($subsystem.getProperty("Default Command") != "None")
        setDefaultCommand(new ${helper.className($subsystem.getProperty("Default Command"))}());
#end
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

